kind: Secret
apiVersion: v1
metadata:
  name: credentials
  namespace: grafana
stringData:
  GF_SECURITY_ADMIN_PASSWORD: CHANGE_ME_TO_A_STRONG_PASSWORD
  GF_SECURITY_ADMIN_USER: CHANGE_ME_TO_A_STRONG_USERNAME
  # TODO: this will be replaced by OAuth login
type: Opaque