# Default values for machinesets.
region: us-east
zones: ["1", "2", "3"]
clusterApiCluster: "REPLACE_ME"
namespace: openshift-machine-api

ibmCloud:
  resourceGroup: "Default"

machinesets:
- name: test-gpu
  autoscaler: false
  minReplicas: 0
  maxReplicas: 3
  replicas: 0
  instanceType: gx2-80x1280x8a100	
  architecture: "amd64"
  taints:
    - key: benchmark.llm-d.ai/test-gpu-amd64
      effect: NoSchedule
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: "benchmark.llm-d.ai/test-gpu-amd64=true"
    capacity.cluster-autoscaler.kubernetes.io/gpu-type: "nvidia.com/gpu"
    capacity.cluster-autoscaler.kubernetes.io/gpu-count: "2"
    capacity.cluster-autoscaler.kubernetes.io/dra-driver: "gpu.nvidia.com"
  nodeLabels:
    benchmark.llm-d.ai/test-gpu-amd64: "true"
- name: test-cpu-amd64
  autoscaler: false # autoscale from zero is not supported for IBM Cloud
  minReplicas: 0
  maxReplicas: 3
  replicas: 0
  instanceType: "cx2d-16x32"
  architecture: "amd64"
  taints:
    - key: benchmark.llm-d.ai/test-cpu-amd64
      effect: NoSchedule
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: "benchmark.llm-d.ai/test-cpu-amd64=true"
  nodeLabels:
    benchmark.llm-d.ai/test-cpu-amd64: "true"
- name: infra-amd64
  autoscaler: true
  minReplicas: 1
  maxReplicas: 3
  replicas: 0
  instanceType: "cx2d-16x32"
  architecture: "amd64"
  annotations:
    capacity.cluster-autoscaler.kubernetes.io/labels: "benchmark.llm-d.ai/infra-amd64=true"
  nodeLabels:
    benchmark.llm-d.ai/infra-amd64: "true"

# Cluster autoscaler settings
autoscaler:
  enableScaleDown: true
