#TODO: cloud provider specific secret for loki
kind: Secret
apiVersion: v1
metadata:
  name: loki-s3
  namespace: netobserv   
stringData:
  access_key_id: <your-access-key-id>
  access_key_secret: <your-access-key-secret>
  bucketnames: <your-bucket-name>
  endpoint: <your-endpoint-url>
  region: <your-region>