apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
spec:
  tolerations:
    - key: benchmark.llm-d.ai/storage
      effect: NoSchedule
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: benchmark.llm-d.ai/storage
            operator: In
            values:
              - 'true'
  storageClassDevices:
    - storageClassName: "local-sc"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/vdb
        - /dev/vdc