# Additional CatalogSources (required for pre-release OCP)
additionalCatalogSources:
  - displayName: Certified Operators (4.19)
    image: registry.redhat.io/redhat/certified-operator-index:v4.19
    name: certified-operators-4-19
    namespace: openshift-marketplace
    publisher: Red Hat
  - displayName: Red Hat Operators (4.19)
    image: registry.redhat.io/redhat/redhat-operator-index:v4.19
    name: redhat-operators-4-19
    namespace: openshift-marketplace
    publisher: Red Hat

cliImage: registry.ci.openshift.org/origin/4.16:cli
namespace: openshift-marketplace

# Operators to install
operators:
  - channel: stable-v1
    name: openshift-cert-manager-operator
    namespace: cert-manager-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - channel: latest
    consolePlugins:
      - gitops-plugin
    name: openshift-gitops-operator
    namespace: openshift-gitops-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - channel: stable
    name: openshift-nfd # nfd
    namespace: openshift-nfd
    source: redhat-operators-4-19
    sourceNamespace: openshift-marketplace
    targetNamespace: openshift-nfd
  - channel: v25.3
    name: gpu-operator-certified
    namespace: nvidia-gpu-operator
    source: certified-operators-4-19
    sourceNamespace: openshift-marketplace
    targetNamespace: nvidia-gpu-operator
  - channel: stable-v1.0
    name: leader-worker-set
    namespace: openshift-lws-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    targetNamespace: openshift-lws-operator
  - channel: latest
    consolePlugins:
      - pipelines-console-plugin
    name: openshift-pipelines-operator-rh # no -rh?
    namespace: openshift-pipelines
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - channel: stable
    name: sriov-network-operator
    namespace: openshift-sriov-network-operator
    source: redhat-operators-4-19
    sourceNamespace: openshift-marketplace
    targetNamespace: openshift-sriov-network-operator
  - channel: stable
    name: rhcl-operator
    namespace: kuadrant-system
    source: redhat-operators-4-19
    sourceNamespace: openshift-marketplace
  - channel: stable
    name: cluster-kube-descheduler-operator
    namespace: openshift-kube-descheduler-operator
    source: redhat-operators-4-19
    sourceNamespace: openshift-marketplace
    targetNamespace: openshift-kube-descheduler-operator
  - channel: stable
    name: openshift-custom-metrics-autoscaler-operator
    namespace: openshift-keda
    operatorName: openshift-custom-metrics-autoscaler-operator
    source: redhat-operators-4-19
    sourceNamespace: openshift-marketplace
  - channel: stable
    name: netobserv-operator
    namespace: openshift-netobserv-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - channel: v5
    name: grafana-operator
    namespace: grafana-operator
    source: community-operators
    sourceNamespace: openshift-marketplace
  - channel: stable-6.3
    name: loki-operator
    namespace: openshift-operators-redhat
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  - channel: stable
    name: multiarch-tuning-operator
    namespace: openshift-multiarch-tuning-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
