apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-provisioner
  namespace: nfs-provisioner
  labels:
    app: nfs-server-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-server-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      nodeSelector:
        benchmark.llm-d.ai/storage: "true"
      tolerations:
        - key: benchmark.llm-d.ai/storage
          effect: NoSchedule
      containers:
      - name: nfs-server
        image: docker.io/janeczku/nfs-ganesha:latest
        ports:
        - name: nfs
          containerPort: 2049
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
              - DAC_READ_SEARCH
              - DAC_OVERRIDE
        volumeMounts:
        - name: nfs-storage
          mountPath: /data/nfs
        readinessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 2049
          initialDelaySeconds: 30
          periodSeconds: 10
      - name: nfs-provisioner
        image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        volumeMounts:
        - name: nfs-storage
          # This path is constant in the nfs-subdir-external-provisioner code
          mountPath: /persistentvolumes
        args:
          - -v
          - '4'
        env:
        - name: PROVISIONER_NAME
          value: nfs-provisioner/nfs
        - name: NFS_SERVER
          # Must match the clusterIP defined in nfs-server-service.yaml
          value: "172.30.250.250"
          # NFS_PATH is used for the volumeSource of the PV. It must match the nfs-server container's path
        - name: NFS_PATH
          value: /
        securityContext:
          runAsUser: 0
      volumes:
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-server-storage
