{{- $region := .Values.region -}}
{{- $zones := .Values.zones -}}
{{- range $i, $machineset := .Values.machinesets }}
  {{- range $j, $zone := $zones }}
  {{- $name := printf "%s-%s-%s" $machineset.name $region $zone }}
  {{- if $machineset.autoscaler }}
---
apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
spec:
  minReplicas: {{ $machineset.minReplicas | default 0 }}
  maxReplicas: {{ $machineset.maxReplicas | default 3 }}
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: {{ $name }}
    {{- end }}
  {{- end }}
{{- end }}
