kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - namespace.yaml
  - https://github.com/kubernetes-sigs/gateway-api-inference-extension/config/crd/?ref=v1.0.1

namespace: experiment-01