apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vllm
  namespace: redhat-ods-applications
spec:
  podSelector: {}
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
  policyTypes:
    - Ingress
