{
 "title": "vLLM - LLM-D - WVA",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vllm:e2e_request_latency_seconds_bucket,namespace)"
    }
   },
   { "name": "model_name", "query": { "query": "label_values(model_name)" } },
   { "name": "variant_name", "query": { "query": "label_values(variant_name)" } },
   { "name": "accelerator_type", "query": { "query": "label_values(accelerator_type)" } },
   {
    "name": "gpu_node_hostname",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   },
   {
    "name": "rate_interval",
    "query": "1s, 2s, 4s, 8s, 10s, 20s, 30s, 1m, 5m, 10m, 15m, 20m, 30m, 1h"
   },
   {
    "name": "candle_stick_min_step",
    "query": "1s, 2s, 4s, 8s, 10s, 20s, 30s, 1m, 5m, 10m, 15m, 20m, 30m, 1h"
   },
   {
    "name": "stacked_charts_min_step",
    "query": "1s, 2s, 4s, 8s, 10s, 20s, 30s, 1m, 5m, 10m, 15m, 20m, 30m, 1h"
   }
  ]
 },
 "panels": [
  { "title": "Library Panels (Imported)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU/Mem (all involved GPU nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "CPU (overall)",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (mode) (\n  irate(node_cpu_seconds_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])\n) /\n  ignoring(mode)\n  group_left\nsum (\n  irate(node_cpu_seconds_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])\n)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage (overall)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_MemFree_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Buffers_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Cached_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Slab_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_PageTables_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_SwapCached_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (User)"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (PageTables)"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (SwapCache)"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (Slab)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (Cache)"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (Buffers)"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (Free)"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_SwapFree_bytes{instance=~\"$gpu_node_hostname\"})",
     "legendFormat": "{{instance}} (Swap)"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$gpu_node_hostname\"}",
     "legendFormat": "{{instance}} (Corrupted)"
    }
   ]
  },
  {
   "title": "CPU/Mem (per node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage ($gpu_node_hostname)",
     "type": "timeseries",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 15 },
     "repeat": "gpu_node_hostname",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_MemFree_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Buffers_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Cached_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_Slab_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_PageTables_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_SwapCached_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (User)"
      },
      {
       "expr": "node_memory_PageTables_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (PageTables)"
      },
      {
       "expr": "node_memory_SwapCached_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (SwapCache)"
      },
      {
       "expr": "node_memory_Slab_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (Slab)"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (Cache)"
      },
      {
       "expr": "node_memory_Buffers_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (Buffers)"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (Free)"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~\"$gpu_node_hostname\"} - node_memory_SwapFree_bytes{instance=~\"$gpu_node_hostname\"})",
       "legendFormat": "{{instance}} (Swap)"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{instance=~\"$gpu_node_hostname\"}",
       "legendFormat": "{{instance}} (Corrupted)"
      }
     ]
    },
    {
     "title": "CPU ($gpu_node_hostname)",
     "type": "barchart",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 36 },
     "repeat": "gpu_node_hostname",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (instance, mode) (\n  irate(node_cpu_seconds_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])\n) /ignoring(mode) group_left sum by (instance) (\n  irate(node_cpu_seconds_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])\n) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "CPU/Mem (per vllm replica)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU usage per replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", pod=~\"$variant_name.*\", container=\"vllm\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage per replica (relative to host node capacity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", pod=~\"$variant_name.*\", container=\"vllm\"}\n/ on (node) group_left\nmachine_cpu_cores",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Mem usage per replica",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, container, node, namespace) (\n  container_memory_usage_bytes{namespace=~\"$namespace\", container=\"vllm\", pod=~\"$variant_name.*\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory usage per replica (relative to host node capacity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod, container, node, namespace) (\n  container_memory_usage_bytes{namespace=~\"$namespace\", container!=\"\", pod=~\"$variant_name.*\"}\n)/ on (node) group_left\nsum by (node) (\n  label_replace(\n    node_memory_MemTotal_bytes{},\n    \"node\", \"$1\",       # new label \"node\"\n    \"instance\", \"(.*)\"  # extract value from label \"instance\"\n  )\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{modelName}} ({{device}}@{{Hostname}})"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Util.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{modelName}} ({{device}}@{{Hostname}})"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{modelName}} ({{device}}@{{Hostname}})"
    }
   ]
  },
  {
   "title": "GPU Tensor Core Util.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{modelName}} ({{device}}@{{Hostname}})"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{exported_namespace=~\"$namespace\"}",
     "legendFormat": "{{modelName}} ({{device}}@{{Hostname}})"
    }
   ]
  },
  { "title": "I/O (Net, Disk, ...)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])*8",
     "legendFormat": "{{device}}@{{instance}} - Rx in"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])*8",
     "legendFormat": "{{device}}@{{instance}} - Tx out"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-irate(node_disk_read_bytes_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])",
     "legendFormat": "{{device}}@{{instance}} - Read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])",
     "legendFormat": "{{device}}@{{instance}} - Writes"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "-irate(node_disk_reads_completed_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])",
     "legendFormat": "{{device}}@{{instance}} - Read"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])",
     "legendFormat": "{{device}}@{{instance}} - Writes"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$gpu_node_hostname\"}[$rate_interval])",
     "legendFormat": "{{device}}@{{instance}}"
    }
   ]
  },
  { "title": "Workload Variant Autoscaler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Replicas: Current vs Desired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "wva_current_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"}",
     "legendFormat": "Current Replicas ({{variant_name}} on {{accelerator_type}})"
    },
    {
     "expr": "wva_desired_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"}",
     "legendFormat": "Desired Replicas ({{variant_name}} on {{accelerator_type}})"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$namespace\"}",
     "legendFormat": "HPA Max Replicas ({{horizontalpodautoscaler}})"
    }
   ]
  },
  {
   "title": "Current vs Desired",
   "type": "stat",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wva_current_replicas{variant_name=~\"$variant_name\",accelerator_type=~\"$accelerator_type\"}",
     "legendFormat": "Current Replicas ({{variant_name}} on {{accelerator_type}})"
    },
    {
     "expr": "wva_desired_ratio{variant_name=~\"$variant_name\",accelerator_type=~\"$accelerator_type\"}",
     "legendFormat": "Desired Ratio ({{variant_name}} on {{accelerator_type}})"
    }
   ]
  },
  {
   "title": "WVA Reconciliation latency",
   "type": "candlestick",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"variantAutoscaling\"}[$__rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"variantAutoscaling\"}[$__rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"variantAutoscaling\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"variantAutoscaling\"}[$__rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(controller_runtime_reconcile_time_seconds_bucket{controller=\"variantAutoscaling\"}[$__rate_interval])))",
     "legendFormat": "P10"
    }
   ]
  },
  {
   "title": "WVA Reconciliation results",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{controller=\"variantAutoscaling\"}[$rate_interval])",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{controller=\"variantAutoscaling\"}[$rate_interval])",
     "legendFormat": "error"
    }
   ]
  },
  { "title": "vLLM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Load Generator SIgnal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=~\"$namespace\"} == 1 and\n  on (namespace, pod)\n  kube_pod_labels{\n    namespace=~\"$namespace\",label_tekton_dev_pipeline_task=\"load-test\", label_benchmark_running=\"true\"\n  }\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Load Generator Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=~\"$namespace\"} == 1 and\n  on (namespace, pod)\n  kube_pod_labels{\n    namespace=~\"$namespace\",label_tekton_dev_pipeline_task=\"load-test\", label_benchmark_running=\"true\"\n  }\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "E2E Request Latency ",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Avg. E2E Latency per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:e2e_request_latency_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n/\nrate(vllm:e2e_request_latency_seconds_count{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ITL",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(vllm:inter_token_latency_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:inter_token_latency_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:inter_token_latency_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    },
    {
     "expr": "wva_current_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"} and (delta(wva_current_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"}[30s]) > 0)",
     "legendFormat": "Current Replicas - Scale out (y2)"
    },
    {
     "expr": "wva_current_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"} and (delta(wva_current_replicas{variant_name=\"$variant_name\", accelerator_type=~\"$accelerator_type\"}[30s]) < 0)",
     "legendFormat": "Current Replicas - Scale in (y2)"
    }
   ]
  },
  {
   "title": "Avg. ITL per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:inter_token_latency_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n/\nrate(vllm:inter_token_latency_seconds_count{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TTFT",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Avg. TTFT per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:time_to_first_token_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n/\nrate(vllm:time_to_first_token_seconds_count{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Prefill time",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_prefill_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:request_prefill_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_prefill_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:request_prefill_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le) (rate(vllm:request_prefill_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:request_prefill_time_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:request_prefill_time_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Decode time",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_decode_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:request_decode_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_decode_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:request_decode_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.10, sum by(le) (rate(vllm:request_decode_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:request_decode_time_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:request_decode_time_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(vllm:request_queue_time_seconds_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:request_queue_time_seconds_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:request_queue_time_seconds_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Time per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(vllm:request_queue_time_seconds_sum{model_name=\"$model_name\", namespace=~\"$namespace\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(vllm:request_max_num_generation_tokens_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(vllm:request_max_num_generation_tokens_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:request_max_num_generation_tokens_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(vllm:request_max_num_generation_tokens_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.1, sum by(le) (rate(vllm:request_max_num_generation_tokens_bucket{model_name=\"$model_name\"}[$rate_interval])))",
     "legendFormat": "P10"
    },
    {
     "expr": "sum by(model_name) (\n  rate(vllm:request_max_num_generation_tokens_sum{model_name=\"$model_name\"}[$rate_interval])\n)\n/\nsum by(model_name) (\n  rate(vllm:request_max_num_generation_tokens_count{model_name=\"$model_name\"}[$rate_interval])\n)",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Max Generation Token in Sequence Group per instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "rate(vllm:request_max_num_generation_tokens_sum{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Token Throughput (Generated Tokens/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Token Throughput (Prompt Tokens/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total{model_name=\"$model_name\"}[$rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "vLLM Scheduler State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "targets": [
    {
     "expr": "vllm:num_requests_running{model_name=\"$model_name\"}",
     "legendFormat": "Running ({{instance}})"
    },
    {
     "expr": "vllm:num_requests_waiting{model_name=\"$model_name\"}",
     "legendFormat": "Waiting ({{instance}})"
    },
    {
     "expr": "sum(vllm:num_requests_running{model_name=\"$model_name\"})\n",
     "legendFormat": "Running (total)"
    },
    {
     "expr": "sum(vllm:num_requests_waiting{model_name=\"$model_name\"})\n",
     "legendFormat": "Waiting (total)"
    }
   ]
  },
  {
   "title": "vLLM KV Cache utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vllm:kv_cache_usage_perc{model_name=\"$model_name\"}",
     "legendFormat": "KV Cache Util. ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Prompt Length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_prompt_tokens_bucket{model_name=\"$model_name\", namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Generated Tokens Length",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "targets": [
    {
     "expr": "sum by(le) (increase(vllm:request_generation_tokens_bucket{model_name=\"$model_name\", namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response result by Finish Reason",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "targets": [
    {
     "expr": "sum by(finished_reason) (increase(vllm:request_success_total{model_name=\"$model_name\", namespace=~\"$namespace\"}[$rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}