apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: model-storage
    namespace: experiment-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: nfs-client
  volumeMode: Filesystem